apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongodb-client
  name: mongodb-client
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: mongodb
  type: NodePort
status:
  loadBalancer: {}
